# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3.4'

#Define services
services:

  #Back-end Spring Boot Application
  app-server:
    #The docker file in app-server build the jar and provides the docker image with the following name.
    image: leandropldev/loja-server
    restart: always
    build: ./app-server
    working_dir: /app-server/app-loja
    #Environment variables for Spring Boot Application.
    environment: 
      TZ: America/Sao_Paulo
      SPRING_ENVIRONMENT: prod
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: loja_db
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    command: mvn spring-boot:run
    networks:
      - loja-network 
      
  #Fron-end Angular Application
  #app-client:
  #  build: ./app-client
  #  container_name: app-client
  #  ports:
  #    - 4200:80
  #  links:
  #    - app-server

networks: 
  loja-network:
    driver: bridge

#Volumes for DB data
volumes:
  project-data: