server:
  servlet:
    context-path: /loja-da-joyce
    
spring:  h2:    console:      path: /h2      enabled: true  datasource:    username: sa
    password: 
    url: jdbc:h2:file:/E:/h2-db
    driver-class-name: org.h2.Driver  jpa:    hibernate:      ddl-auto: update