server:
  servlet:
    context-path: /loja-da-joyce
    
spring:  h2:    console:      path: /h2      enabled: true  datasource:    username: sa
    password: 
    driver-class-name: org.h2.Driver  jpa:    hibernate:      ddl-auto: none